name: Run automation tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_HOME: ~/Android/Sdk
      ANDROID_SDK_ROOT: ~/Android/Sdk
      ANDROID_AVD_HOME: /home/runner/.config/.android/avd/

    steps:  
    - name: Update packages
      run: sudo apt-get update

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Install KVM on Linux
      run: |
        sudo apt-get install cpu-checker
        sudo apt-get install -y qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils
    - name: Set chmod kvm
      run: |      
       sudo chmod o+rw /dev/kvm    
    - name: Install Node.js and npm
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Appium
      run: npm install -g appium

    - name: Install UiAutomator2
      run: appium driver install uiautomator2

    - name: Curl cmdline-tools from Android.tar.gz
      run: cd && curl -O -L https://github.com/fahleiro/appium-avd-action-ubuntu/releases/download/appium-avd-action-ubuntu-1.0.0/Android.tar.gz
      
    - name: Descomprimir Android.tar.gz
      run: tar -xzf ~/Android.tar.gz -C ~ && echo "Descompressão de Android concluída."

    - name: Install Android dependencies
      run: |
        chmod +x ~/Android/Sdk/cmdline-tools/latest/bin/sdkmanager
        yes | ~/Android/Sdk/cmdline-tools/latest/bin/sdkmanager --licenses
        ~/Android/Sdk/cmdline-tools/latest/bin/sdkmanager --install "platform-tools"
        ~/Android/Sdk/cmdline-tools/latest/bin/sdkmanager --install "emulator"
        ~/Android/Sdk/cmdline-tools/latest/bin/sdkmanager --install "build-tools;30.0.3"
        ~/Android/Sdk/cmdline-tools/latest/bin/sdkmanager --install "platforms;android-27"
        ~/Android/Sdk/cmdline-tools/latest/bin/sdkmanager --install "system-images;android-30;default;x86_64"
    - name: Create Android Virtual Device (AVD)
      run: |
        chmod +x ~/Android/Sdk/cmdline-tools/latest/bin/avdmanager
        ~/Android/Sdk/cmdline-tools/latest/bin/avdmanager create avd -n device-name -k "system-images;android-30;default;x86_64" -d pixel_4
    
    - name: Run Android Virtual Device (AVD)
      run: |
        chmod +x ~/Android/Sdk/emulator/emulator
        chmod +x ~/Android/Sdk/emulator
        ~/Android/Sdk/emulator/emulator -avd device-name -port 5554 -no-window -no-audio -no-boot-anim &
    - name: Validating AVD ready
      run: |
        chmod +x ~/Android/Sdk/platform-tools/adb      
        status=$(~/Android/Sdk/platform-tools/adb devices | grep -v "List of devices attached")
        while ! echo "$status" | grep -q "device"; do
          echo "Emulator is not ready, waiting..."
          sleep 5
          status=$(~/Android/Sdk/platform-tools/adb devices | grep -v "List of devices attached")
        done
        echo "Emulator is online!"
        echo "$status"

      #specifies about project

    - name: Set up settings.xml
      run: |
        echo "<settings xmlns=\"http://maven.apache.org/SETTINGS/1.0.0\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd\">
              <servers>
                <server>
                  <id>github</id>
                  <username>${{secrets.GH_ACTOR}}</username>
                  <password>${{secrets.GH_PTOKEN}}</password>
                </server>
              </servers>
            </settings>" > $HOME/.m2/settings.xml 
            
    - name: Git clone
      run: |      
        cd && git clone -b mobile-automate-dev https://github.com/fahleiro/java-dev.git && ls
        

    - name: Install .apk in emulator
      run: |
        cd ~/java-dev
        while ! ~/Android/Sdk/platform-tools/adb install app-debug.apk; do
          echo "Failed to install. Retrying..."
          sleep 5
        done

    - name: Set Android environment variables and cmdline tools path
      run: |
        echo 'export ANDROID_HOME=~/Android/Sdk' >> $GITHUB_ENV
        echo 'export ANDROID_SDK_ROOT=~/Android/Sdk' >> $GITHUB_ENV
        echo 'export PATH=~/Android/Sdk/cmdline-tools/latest:~/Android/Sdk:~/Android/Sdk/tools:~/Android/Sdk/tools/bin:~/Android/Sdk/platform-tools:$PATH' >> $GITHUB_ENV
        echo 'export PATH=~/Android/Sdk/cmdline-tools/latest:$PATH' >> ~/.bashrc && source ~/.bashrc
        echo 'export PATH=~/Android/Sdk:$PATH' >> ~/.bashrc && source ~/.bashrc
    
    - name: Run tests
      run: |
        source ~/.bashrc
        cd ~/java-dev && mvn test -Dtest=Runner.java

    