name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:  
    - name: Checkout code to mobile-automate-dev
      uses: actions/checkout@v4.1.2
      with:
        ref: mobile-automate-dev

    - name: Print current branch
      run: echo "Current branch is $(git rev-parse --abbrev-ref HEAD)"

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Print settings.xml
      run: cat $HOME/.m2/settings.xml

    - name: Set up Maven
      run: |
        echo "<settings xmlns=\"http://maven.apache.org/SETTINGS/1.0.0\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd\">
              <servers>
                <server>
                  <id>github</id>
                  <username>${{secrets.GH_ACTOR}}</username>
                  <password>${{secrets.GH_PTOKEN}}</password>
                </server>
              </servers>
            </settings>" > $HOME/.m2/settings.xml

    - name: Print settings.xml
      run: cat $HOME/.m2/settings.xml  

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
